import bcrypt from "bcryptjs";
import { readDb, writeDb } from "./db.js";

const products = [
  {
    id: "p1",
    brand: "Bloominc",
    name: "Bluebell Gray",
    category: "contact-lenses",
    section: "bloominc",
    priceOriginal: 169000,
    priceSale: 129000,
    badge: "SALE",
    image: "/placeholders/lens-gray.svg",
    colorSwatch: "#9ca3af",
    description:
      "자연스러운 그레이 톤의 데일리 렌즈. 14.2mm 직경, PC 하이드로겔 소재.",
  },
  {
    id: "p2",
    brand: "Bloominc",
    name: "Posy Choco",
    category: "contact-lenses",
    section: "bloominc",
    priceOriginal: 169000,
    priceSale: 129000,
    badge: "SALE",
    image: "/placeholders/lens-choco.svg",
    colorSwatch: "#78350f",
  },
  {
    id: "p3",
    brand: "Bloominc",
    name: "Daisy Gray",
    category: "contact-lenses",
    section: "bloominc",
    priceOriginal: 169000,
    priceSale: 129000,
    badge: "SALE",
    image: "/placeholders/lens-gray.svg",
    colorSwatch: "#6b7280",
  },
  {
    id: "p4",
    brand: "Bloominc",
    name: "Moist Clear",
    category: "contact-lenses",
    section: "bloominc",
    priceOriginal: 169000,
    priceSale: 129000,
    badge: "SALE",
    image: "/placeholders/lens-clear.svg",
    colorSwatch: "#e5e7eb",
  },
  {
    id: "p5",
    brand: "Bloominc",
    name: "Freesia Ash Brown",
    category: "contact-lenses",
    section: "best-seller",
    priceOriginal: 169000,
    priceSale: 129000,
    badge: "SALE",
    image: "/placeholders/lens-brown.svg",
    colorSwatch: "#a16207",
  },
  {
    id: "p6",
    brand: "Bloominc",
    name: "Calla Choco",
    category: "contact-lenses",
    section: "best-seller",
    priceOriginal: 169000,
    priceSale: 129000,
    badge: "SALE",
    image: "/placeholders/lens-choco.svg",
    colorSwatch: "#92400e",
  },
  {
    id: "p7",
    brand: "Eyesm",
    name: "Ocher Brown",
    category: "contact-lenses",
    section: "best-seller",
    priceOriginal: 122000,
    priceSale: 96000,
    badge: "SALE",
    image: "/placeholders/lens-brown.svg",
    colorSwatch: "#b45309",
  },
  {
    id: "p8",
    brand: "Bloominc",
    name: "Ivy Brown",
    category: "contact-lenses",
    section: "best-seller",
    priceOriginal: 169000,
    priceSale: 129000,
    badge: "NEW",
    image: "/placeholders/lens-brown.svg",
    colorSwatch: "#854d0e",
  },
  {
    id: "p9",
    brand: "Rohto",
    name: "Rohto Lycee Contact 8ml",
    category: "solutions",
    section: "solutions",
    priceOriginal: 134000,
    priceSale: 129000,
    badge: "SALE",
    image: "/placeholders/solution.svg",
    colorSwatch: "#3b82f6",
  },
  {
    id: "p10",
    brand: "Bio True",
    name: "Bio True MPS 300ml",
    category: "solutions",
    section: "solutions",
    priceOriginal: 135000,
    priceSale: 120000,
    badge: "SALE",
    image: "/placeholders/solution.svg",
    colorSwatch: "#06b6d4",
  },
  {
    id: "p11",
    brand: "Renu",
    name: "Renu Fresh MPS 355 ml",
    category: "solutions",
    section: "solutions",
    priceOriginal: 110000,
    priceSale: 106000,
    badge: null,
    image: "/placeholders/solution.svg",
    colorSwatch: "#0ea5e9",
  },
  {
    id: "p12",
    brand: "Lens Care",
    name: "Anya 3 in 1 Lens Case",
    category: "accessories",
    section: "accessories",
    priceOriginal: 49000,
    priceSale: 39000,
    badge: "SALE",
    image: "/placeholders/accessory.svg",
    colorSwatch: "#ec4899",
  },
  {
    id: "p13",
    brand: "Lens Care",
    name: "Cute 2-in-1 Travel Lenscase",
    category: "accessories",
    section: "accessories",
    priceOriginal: 42000,
    priceSale: 29000,
    badge: "SALE",
    image: "/placeholders/accessory.svg",
    colorSwatch: "#f472b6",
  },
  {
    id: "p14",
    brand: "Lens Care",
    name: "Pick & Pop Lens Applicator",
    category: "accessories",
    section: "accessories",
    priceOriginal: 60000,
    priceSale: 39000,
    badge: "SALE",
    image: "/placeholders/accessory.svg",
    colorSwatch: "#db2777",
  },
  {
    id: "p15",
    brand: "Bundle Accessories",
    name: "Travel Essentials A",
    category: "bundles",
    section: "bundles",
    priceOriginal: 144400,
    priceSale: 139400,
    badge: "SALE",
    image: "/placeholders/bundle.svg",
    colorSwatch: "#be185d",
  },
  {
    id: "p16",
    brand: "Bundle Accessories",
    name: "Complete Kit B",
    category: "bundles",
    section: "bundles",
    priceOriginal: 226500,
    priceSale: 199000,
    badge: "SALE",
    image: "/placeholders/bundle.svg",
    colorSwatch: "#9d174d",
  },
  {
    id: "p17",
    brand: "Bundle Accessories",
    name: "Lensmate Pack",
    category: "bundles",
    section: "bundles",
    priceOriginal: 58000,
    priceSale: 43500,
    badge: "25%",
    image: "/placeholders/bundle.svg",
    colorSwatch: "#831843",
  },
];

async function seed() {
  const hash = await bcrypt.hash("admin1234", 10);
  const demoHash = await bcrypt.hash("demo1234", 10);

  const db = {
    users: [
      {
        id: "u-admin",
        email: "admin@eyesight.local",
        passwordHash: hash,
        firstName: "Admin",
        lastName: "ERP",
        role: "admin",
        createdAt: new Date().toISOString(),
      },
      {
        id: "u-demo",
        email: "demo@eyesight.local",
        passwordHash: demoHash,
        firstName: "고원석",
        lastName: "Demo",
        role: "customer",
        createdAt: new Date().toISOString(),
      },
    ],
    products,
    orders: [],
  };

  writeDb(db);
  console.log("Seed complete:");
  console.log("  admin@eyesight.local / admin1234 (ERP)");
  console.log("  demo@eyesight.local / demo1234 (고객)");
  console.log(`  ${products.length} products`);
}

seed();
