import bcrypt from "bcryptjs";
import { readDb, writeDb } from "./db.js";
import { EXTRA_PRODUCTS } from "./extra-products.js";

const products = [
  {
    id: "p1",
    brand: "Bloominc",
    name: "Bluebell Gray",
    category: "contact-lenses",
    section: "bloominc",
    priceOriginal: 169000,
    priceSale: 129000,
    badge: "SALE",
    image: "/products/lens-bluebell-gray.png",
    colorSwatch: "#9ca3af",
    description:
      "자연스러운 그레이 톤의 데일리 렌즈. 14.2mm 직경, PC 하이드로겔 소재.",
  },
  {
    id: "p2",
    brand: "Bloominc",
    name: "Posy Choco",
    category: "contact-lenses",
    section: "bloominc",
    priceOriginal: 169000,
    priceSale: 129000,
    badge: "SALE",
    image: "/products/lens-posy-choco.png",
    colorSwatch: "#78350f",
  },
  {
    id: "p3",
    brand: "Bloominc",
    name: "Daisy Gray",
    category: "contact-lenses",
    section: "bloominc",
    priceOriginal: 169000,
    priceSale: 129000,
    badge: "SALE",
    image: "/products/lens-daisy-gray.png",
    colorSwatch: "#6b7280",
  },
  {
    id: "p4",
    brand: "Bloominc",
    name: "Moist Clear",
    category: "contact-lenses",
    section: "bloominc",
    priceOriginal: 169000,
    priceSale: 129000,
    badge: "SALE",
    image: "/products/lens-moist-clear.png",
    colorSwatch: "#e5e7eb",
  },
  {
    id: "p5",
    brand: "Bloominc",
    name: "Freesia Ash Brown",
    category: "contact-lenses",
    section: "best-seller",
    priceOriginal: 169000,
    priceSale: 129000,
    badge: "SALE",
    image: "/products/lens-freesia-brown.png",
    colorSwatch: "#a16207",
  },
  {
    id: "p6",
    brand: "Bloominc",
    name: "Calla Choco",
    category: "contact-lenses",
    section: "best-seller",
    priceOriginal: 169000,
    priceSale: 129000,
    badge: "SALE",
    image: "/products/lens-calla-choco.png",
    colorSwatch: "#92400e",
  },
  {
    id: "p7",
    brand: "Eyesm",
    name: "Ocher Brown",
    category: "contact-lenses",
    section: "best-seller",
    priceOriginal: 122000,
    priceSale: 96000,
    badge: "SALE",
    image: "/products/lens-ocher-brown.png",
    colorSwatch: "#b45309",
  },
  {
    id: "p8",
    brand: "Bloominc",
    name: "Ivy Brown",
    category: "contact-lenses",
    section: "best-seller",
    priceOriginal: 169000,
    priceSale: 129000,
    badge: "NEW",
    image: "/products/lens-ivy-brown.png",
    colorSwatch: "#854d0e",
  },
  {
    id: "p9",
    brand: "Rohto",
    name: "Rohto Lycee Contact 8ml",
    category: "solutions",
    section: "solutions",
    priceOriginal: 134000,
    priceSale: 129000,
    badge: "SALE",
    image: "/products/product-rohto-lycee.png",
    colorSwatch: "#3b82f6",
  },
  {
    id: "p10",
    brand: "Bio True",
    name: "Bio True MPS 300ml",
    category: "solutions",
    section: "solutions",
    priceOriginal: 135000,
    priceSale: 120000,
    badge: "SALE",
    image: "/products/product-biotrue-mps.png",
    colorSwatch: "#06b6d4",
  },
  {
    id: "p11",
    brand: "Renu",
    name: "Renu Fresh MPS 355 ml",
    category: "solutions",
    section: "solutions",
    priceOriginal: 110000,
    priceSale: 106000,
    badge: null,
    image: "/products/product-renu-fresh.png",
    colorSwatch: "#0ea5e9",
  },
  {
    id: "p12",
    brand: "Lens Care",
    name: "Anya 3 in 1 Lens Case",
    category: "accessories",
    section: "accessories",
    priceOriginal: 49000,
    priceSale: 39000,
    badge: "SALE",
    image: "/products/product-lens-case-anya.png",
    colorSwatch: "#ec4899",
  },
  {
    id: "p13",
    brand: "Lens Care",
    name: "Cute 2-in-1 Travel Lenscase",
    category: "accessories",
    section: "accessories",
    priceOriginal: 42000,
    priceSale: 29000,
    badge: "SALE",
    image: "/products/product-travel-case.png",
    colorSwatch: "#f472b6",
  },
  {
    id: "p14",
    brand: "Lens Care",
    name: "Pick & Pop Lens Applicator",
    category: "accessories",
    section: "accessories",
    priceOriginal: 60000,
    priceSale: 39000,
    badge: "SALE",
    image: "/products/product-lens-applicator.png",
    colorSwatch: "#db2777",
  },
  {
    id: "p18",
    brand: "Lens Care",
    name: "Sterile Saline 100ml",
    category: "accessories",
    section: "accessories",
    priceOriginal: 45000,
    priceSale: 35000,
    badge: "SALE",
    image: "/products/product-renu-fresh.png",
    colorSwatch: "#38bdf8",
  },
  {
    id: "p19",
    brand: "Lens Care",
    name: "Ultra Soft Lens Wipes 30pcs",
    category: "accessories",
    section: "accessories",
    priceOriginal: 55000,
    priceSale: 42000,
    badge: "SALE",
    image: "/products/product-biotrue-mps.png",
    colorSwatch: "#22d3ee",
  },
  {
    id: "p20",
    brand: "Lens Care",
    name: "Pink LED Light Mirror",
    category: "accessories",
    section: "accessories",
    priceOriginal: 89000,
    priceSale: 69000,
    badge: "NEW",
    image: "/products/product-lens-case-anya.png",
    colorSwatch: "#f472b6",
  },
  {
    id: "p21",
    brand: "Lens Care",
    name: "Professional Lens Tweezers",
    category: "accessories",
    section: "accessories",
    priceOriginal: 48000,
    priceSale: 36000,
    badge: null,
    image: "/products/product-lens-applicator.png",
    colorSwatch: "#ec4899",
  },
  {
    id: "p22",
    brand: "Lens Care",
    name: "Marble Pattern Lens Case",
    category: "accessories",
    section: "accessories",
    priceOriginal: 52000,
    priceSale: 41000,
    badge: "SALE",
    image: "/products/product-travel-case.png",
    colorSwatch: "#a855f7",
  },
  {
    id: "p15",
    brand: "Bundle Accessories",
    name: "Travel Essentials A",
    category: "bundles",
    section: "bundles",
    priceOriginal: 144400,
    priceSale: 139400,
    badge: "SALE",
    image: "/products/bundle-travel-essentials.png",
    colorSwatch: "#be185d",
  },
  {
    id: "p16",
    brand: "Bundle Accessories",
    name: "Complete Kit B",
    category: "bundles",
    section: "bundles",
    priceOriginal: 226500,
    priceSale: 199000,
    badge: "SALE",
    image: "/products/bundle-complete-kit.png",
    images: [],
    colorSwatch: "#9d174d",
  },
  {
    id: "p17",
    brand: "Bundle Accessories",
    name: "Lensmate Pack",
    category: "bundles",
    section: "bundles",
    priceOriginal: 58000,
    priceSale: 43500,
    badge: "25%",
    image: "/products/bundle-lensmate-pack.png",
    colorSwatch: "#831843",
  },
  ...EXTRA_PRODUCTS,
];

async function seed() {
  const hash = await bcrypt.hash("admin1004", 10);

  const db = {
    users: [
      {
        id: "u-admin",
        email: "dayeon@naver.com",
        passwordHash: hash,
        authProvider: "local",
        googleId: null,
        avatarUrl: null,
        firstName: "다연",
        lastName: "Admin",
        phone: "010-0000-0001",
        address: "서울특별시 강남구 테헤란로 1",
        role: "admin",
        points: 5000,
        loginCount: 12,
        lastLoginAt: new Date().toISOString(),
        createdAt: new Date(Date.now() - 86400000 * 30).toISOString(),
      },
    ],
    products,
    orders: [
      {
        id: "o-demo-1",
        userId: "u-admin",
        status: "paid",
        total: 258000,
        items: [{ productId: "p1", quantity: 2 }],
        createdAt: new Date(Date.now() - 86400000 * 3).toISOString(),
      },
    ],
    carts: [
      {
        userId: "u-admin",
        items: [
          {
            id: "cart-demo-1",
            productId: "p1",
            quantity: 1,
            savedAt: new Date().toISOString(),
          },
          {
            id: "cart-demo-2",
            productId: "p2",
            quantity: 2,
            savedAt: new Date(Date.now() - 3600000).toISOString(),
          },
          {
            id: "cart-demo-3",
            productId: "p3",
            quantity: 1,
            savedAt: new Date(Date.now() - 7200000).toISOString(),
          },
        ],
        updatedAt: new Date().toISOString(),
      },
    ],
  };

  writeDb(db);
  console.log("Seed complete:");
  console.log("  dayeon@naver.com / admin1004 (ERP · 고객 테스트)");
  console.log(`  ${products.length} products`);
}

seed();
